update

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -96,14 +96,17 @@ jobs:
               fi
               $SUDO mv eksctl_download/eksctl /usr/local/bin/
               rmdir eksctl_download
-        - aws-eks/create-cluster:
-            cluster-name: Cluster-${CIRCLE_WORKFLOW_ID:0:7}
-            skip-kubectl-install: false
-            verbose: 3
-            node-type: t2.micro
-            nodes-max: 2
-            ssh-access: false
-            ssh-public-key: ''
+        - run:
+            name: "Creating cluster"
+            command: |
+              echo 'Pre-check before creating...'
+              aws eks describe-cluster --name Cluster-${CIRCLE_WORKFLOW_ID:0:7}
+              if [ $? -ne 0 ]; then
+                echo 'Cluster not found. Creating new cluster...'
+                eksctl create cluster --name Cluster-${CIRCLE_WORKFLOW_ID:0:7} --nodes 3 --nodes-min 1 --nodes-max 5 --region us-east-1
+              else
+                echo 'Cluster existed. Skiping...'
+              fi
         - destroy-env
       
     
